# UAPI Header export list

generic-y += elf.h
generic-y += kvm_para.h
generic-y += shmparam.h
generic-y += timex.h

generated-y += config.h
generated-y += unistd_64.h

# no header-y since we need special user headers handling
# see arch/flux/script/headers.py
