obj-y := bootmem.o mmu.o mmap.o
obj-$(CONFIG_FLUX_HOST_FAULT_REPAIR) += projection.o
obj-$(CONFIG_NUMA) += numa.o
obj-$(CONFIG_FLUX_ELASTIC_MEMORY) += elastic.o
obj-$(CONFIG_FLUX_ELASTIC_MIGRATION) += elastic-policy.o
obj-$(CONFIG_FLUX_FAULT_STATS) += fault_stats.o
obj-$(CONFIG_FLUX_FORK_STATS) += fork_stats.o
