/* SPDX-License-Identifier: GPL-2.0 */
#ifndef __ASM_FLUX_VDSO_CLOCKSOURCE_H
#define __ASM_FLUX_VDSO_CLOCKSOURCE_H

#define VDSO_ARCH_CLOCKMODES VDSO_CLOCKMODE_TSC

#endif /* __ASM_FLUX_VDSO_CLOCKSOURCE_H */
