obj-y += entry.o process.o match.o setup.o syscalls.o signal.o extable.o

obj-y += crypto/

obj-y += lib/

obj-$(CONFIG_SMP) += percpu.o

obj-$(CONFIG_FLUX_UINTR) += uintr.o timer-uintr.o

obj-$(CONFIG_X86_TSC) += tsc.o
